--- #YAML:1.0
name:                JavaScript-Lite
version:             0.04
abstract:            Bare-bones interface to SpiderMonkey ECMAscript API
license:             perl
author:              
    - Tyler MacDonald <japh@crackerjack.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::Exception:               0.27
    Test::More:                    0.8
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
